### PR TITLE
Updated global color variables + fixed formatting

### PR DESCRIPTION
**Pull request by anhduy1202**
# Description
- Renamed Hooks to hooks for naming convention
- Added global color variables with naming similar to acmcsuf.com color variables
- Fixed some formatting ( extra whitespace for props, extra brackets,...)

### CODE REVIEW

**Comment by jaasonw** [comment]
poggers

**Comment by jaasonw** [comment]
NOT POGGERS

**Comment by jaasonw** [comment]
brain no work at 2am i can fix

**Comment by anhduy1202** [comment]
how tf lolol did you resolve merge conflict at verify.tsx

**Comment by jaasonw** [comment]
yes, it's cus hooks didnt really rename

**Comment by anhduy1202** [comment]
hooks sus

**Pull request merged**
